 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [01/Jul/2017 15:25:02] "GET /record/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2017 15:30:02] "GET /record/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2017 15:34:48] "GET /record/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2017 15:35:02] "GET /record/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2017 15:36:11] "GET /record/ HTTP/1.1" 200 -
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "app.py", line 46, in <module>
    app.run(debug=True)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 617, in run_simple
    test_socket.bind((hostname, port))
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
 * Restarting with stat
127.0.0.1 - - [01/Jul/2017 15:38:02] "GET /record/ HTTP/1.1" 200 -
127.0.0.1 - - [01/Jul/2017 15:38:21] "GET /record/ HTTP/1.1" 200 -
